DROP TABLE IF EXISTS Clients;

CREATE TABLE Clients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fathername TEXT NOT NULL,
    mothername TEXT NOT NULL,
    permanentaddress NOT NULL    
);
